 
services:
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9000"
    container_name: clickhouse_consumer
    restart: always
    env_file:
      - path: ./.env